### ISSUE TITLE
Identify the NIC an announced service was discovered on?

### ISSUE THREAD

**Issue by stodge** [faceless2/zeroconf#4]
Our s/w currently listens for mDNS services from a third party system on 2 different NICs. Our s/w processes services from each NIC separately, on different threads.

Is there any way in Zeroconf to identify which NIC an announced service was discovered on?

Thanks

**Comment by faceless2** [comment]
Not quite fixed it seems, hold tight.

**Comment by faceless2** [comment]
OK, these should all be fixed now:
* Zeroconf has a new `setIPv6(boolean)` method to disable IPv6 (and an analogous `setIPv4(boolean)` method too)
* Service has a new `Collection<NetworkInterface> getNetworkInterfaces()` method returning a read-only set
* The fix you made for https://github.com/faceless2/zeroconf/issues/3 was on the right track - I'd missed a pass, basically, but testing all this is very dependent on what is announcing on your local network so I hadn't spotted it locally. I'm quietly confident, but If this doesn't fix it for you please let me know.

Also fixed an exception when cancelling a service, and I've bumped the revision for this set of changes so we're at 1.0.1

**Comment by stodge** [comment]
Thanks, that's awesome. This will really move my prototype along.

Is the JAR published to Maven?

**Comment by faceless2** [comment]
It's not on Maven, but only because I don't use it myself and have never figured it out. Direct download link is in the README.MD however, currently https://faceless2.github.io/zeroconf/dist/zeroconf-1.0.1.jar

**Comment by stodge** [comment]
Understood, and thanks.

**Comment by stodge** [comment]
If I set IPv6 to false, the announced service includes both the IPv4 and IPv6 network interfaces. It's not a problem as I can easily ignore the IPv6 one.

Identifying the network interface for a discovered service works really well if services have already been published before I run my test app. If I publish a new service after my test app is started, the announced service has no network interfaces. I'll try to debug to see what's going on.

Thanks again.

**Comment by faceless2** [comment]
* The `setIPv6()` method was to ensure we only _listen_ on IPv4 addresses, it didn't change the addresses we announce on. Now I write that out, it's clearly the wrong approach. Will fix so it applies to announcements too.

> If I publish a new service after my test app is started, the announced service has no network interfaces.

I have a hunch you're setting an address manually on the service. I'll try and explain.

Conceptually there are three types of service:

1. A service that is announced by someone else. We hear the announcements, and record the addresses on the service, noting (as of a few hours ago) which NIC they came in on.
2. A service that is announced by us and uses the default list of Network Interfaces. In this case the NetworkInterfaces retrieved from the Service are the same as `ZeroConf.getNetworkInterfaces()`, by definition, so we just return that list.
3. A service that is announced by us and uses a manual Network Interface, i.e. you call `addAddress()` on the Service.Builder. In this case the address can be anything - it doesn't have to be a local address - and the list is fixed, so is not updated to reflect any service announcements we hear (because we're the one sending them). In this case the list of Network Interfaces will never be updated - and in fact for non-local addresses, it wouldn't be possible to do so.

I have a hunch you're in situation 3, manually setting the address. Correct?

If you set a manual address and it's local, I suppose we could map that to a set of NetworkInterfaces - it would tell you which NICs the announcement was sent on. If it's not local, well I suppose we could still set it to the list of NICs we announced on. Is that what you're expecting?

**Comment by stodge** [comment]
Apologies if I'm causing confusion with this. We're discovering services published by a third party system. We also have an emulator that uses JmDNS to publish the same services, simulating the third party system. I'm testing zeroconf's functionality against the emulator before I try it with the real third party system. So the results I just reported were from testing services published by the emulator. I'll re-read what you wrote several times and see if the emulator is incorrect. It's likely!

Thanks again.

**Comment by stodge** [comment]
Option 1 applies:
1. A service that is announced by someone else. We hear the announcements, and record the addresses on the service, noting (as of a few hours ago) which NIC they came in on.

**Comment by stodge** [comment]
Would it be possible to instead specify a single network interface (or any number I guess) to listen for services? If I could specify one interface to use, I wouldn't need to check which one was used in the announced callback.

**Comment by faceless2** [comment]
Yes! Absolutely. 
```java
Zeroconf zc = new Zeroconf();
Collection<NetworkInterface> nics = zc.getNetworkInterfaces();
// By default "nics" has all of them, you can remove those you don't want or clear and add those you do. 
nics.clear();
nics.add(mynic);
```
That should sidestep your problem, if not fix it, but it should get you going.

**Comment by stodge** [comment]
You're a legend, thanks! I should have asked that question earlier, and I could have saved you some time. Sorry! 😃

**Comment by stodge** [comment]
I'm getting an IllegalStateException when I do this:

```
Exception in thread "ZeroConfWorker" java.lang.IllegalThreadStateException
	at java.base/java.lang.Thread.start(Thread.java:1525)
	at com.bfo.zeroconf.Zeroconf$ListenerThread.addNetworkInterface(Zeroconf.java:500)
	at com.bfo.zeroconf.Zeroconf$1.add(Zeroconf.java:110)
	at com.bfo.zeroconf.Zeroconf$1.add(Zeroconf.java:99)
```

This is the correct initialisation sequence?

```
        registry = new Zeroconf();
        registry.setIPv6(false);
        registry.setLocalHostName(ip);

        // Remove all NICs and add the one we want to use.
        Collection<NetworkInterface> nics = registry.getNetworkInterfaces();
        nics.clear();
        this.findRequestedNIC(nics);
```

Thanks

**Comment by stodge** [comment]
I suspect the call to isAlive() at line 499 isn't required? It isn't invoked in removeNetworkInterface().

**Comment by faceless2** [comment]
OK, all done. When removing all the NICs the listening thread was being stopped, but of course you can't restart it after that. Now working and rebuilt 1.0.1

**Comment by stodge** [comment]
Ah thanks, I hadn't found the culprit yet. I'll give it a try.

Do you happen to have an account on one of the "buy me a coffee" sites?

**Comment by faceless2** [comment]
Ha! No I don't, but other people testing my work is valuable enough :smile:

**Comment by stodge** [comment]
Let me know if you change your mind. 😃 ☕

**Comment by stodge** [comment]
Listening for services on a single network interface works beautifully in my initial testing. 👍
